[variables]
NIXPACKS_PYTHON_VERSION = "3.9"

[providers]
python = "3.9"

[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "bash"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["chmod +x start.sh"]

[start]
cmd = "./start.sh" 